# Generated by Django 5.1.1 on 2024-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carro_em_estoque_alter_carro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
