# Generated by Django 5.1.1 on 2024-12-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_carro_vendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('numero_cliente', models.CharField(max_length=15)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('cidade_cliente', models.CharField(max_length=255)),
                ('cep_cliente', models.CharField(max_length=10)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=True)),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='carros.carro')),
            ],
        ),
    ]
