# Generated by Django 5.1.1 on 2024-12-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
