# Generated by Django 5.1.1 on 2024-12-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_alter_compra_confirmado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='cidade_cliente',
            new_name='endereco_cliente',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cep_cliente',
        ),
        migrations.AlterField(
            model_name='compra',
            name='confirmado',
            field=models.BooleanField(default=True),
        ),
    ]
