# Generated by Django 5.1.1 on 2024-12-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_rename_cidade_cliente_compra_endereco_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
